### ISSUE TITLE
Obsolete repository description

### ISSUE THREAD

**Issue by atamazian** [Borda/kaggle_image-classify#23]
## 🐛 Bug

Obsolete repository description in "About" sidebox: "Identify the type of disease present on Appletree leafs", although this repository is now a compilation of various classification tasks.

### To Reproduce

Not applicable here.

### Expected behavior

The description should be updated to fit current repository content.

### Additional context

None

**Comment by Borda** [comment]
Yeah, I was a bit out recently... would you be interested in sending a PR with suggested updates? :chipmunk:

**Comment by atamazian** [comment]
How about "Various Kaggle image classification challenges solutions" ?

**Comment by Borda** [comment]
> How about "Various Kaggle image classification challenges solutions" ?

updated, thank you for your suggestion
